<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mdp_camera_bringup</name>
  <version>0.0.1</version>
  <description>Launch and configuration for the Pi camera driver (Picamera2 shared-memory bridge)</description>
  <maintainer email="frieddeli@gmail.com">Ray Shao</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
