plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sc2079.group16.controller'
    compileSdk 34

    defaultConfig {
        applicationId "com.sc2079.group16.controller"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
